SRCS	=	ft_printf.c ft_putnbrbase.c ft_printf_utils.c

MAIN	=	main.c

HEADERS	= 	../libft/libft.a ft_printf.h

CC		= 	gcc -g -Wall -Wextra -Werror

all	:
			$(CC) $(SRCS) $(MAIN) $(HEADERS)
			@echo "Files compiled"
